/*
    created_by: Adityavardhan.N
    created_at: 19-01-2020: 12:20 AM
    Desc: Takes User Input and based on Input Route accordingly 
*/

//  Import NPM Module << readline `npm i readline --save` >>

var readline = require('readline'); // takes input from the User via command line 

// Imports from utils
var MESSAGE    = require('./server/utils/message'),
    ROUTES     = require('./server/apiroutes/routes'),
    CONFIG     = require('./server/config/config'),
    GAME_STATE = require('./server/utils/gameState');

// Building the Command line Tool Interface 
var inputCollector = readline.createInterface({
    input:process.stdin,
    output:process.stdout,
    prompt: 'START> '
});
// Initial message for user
console.log(MESSAGE.INIT_MESSAGE);
/* 'line' event is emitted whenever the 'input' stream receives an end-of-line input
    This usually happens when user presses <Enter> or <Return> keys
*/
// Activate Listeners through line event
inputCollector.on('line', (invoke) =>{
    //calling routes
    ROUTES(invoke.trim(), CONFIG, GAME_STATE)
    // invoke into a new line
    inputCollector.prompt();
});

/* When user wants to exit , input stream receives a <ctrl-C> input
   SIGINT >> SIGINT is generated by the user pressing ctrl + C and is an interrupt 
 */
inputCollector.on('SIGINT', () => {
    inputCollector.question('Are you sure want to exit ? ', (userresponse) => {
        if(userresponse.match(/^y(es)?$/i)) inputCollector.pause();
    });
});

